version: '3.9'
services:
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - mongo_volume:/data/db

  server:
    build:
      dockerfile: ./development.Dockerfile
      context: ./server/
    env_file:
      - ./server/.env.compose
    volumes:
      - ./server/src:/app/src
      - ./server/node_modules:/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  # frontend:
  #   depends_on:
  #     - server
volumes:
  mongo_volume: